### ISSUE TITLE
make motion planning consistent

### ISSUE THREAD

**Issue by akshaykulkarni07** [IvLabs/resources#12]
Following changes are required in motion planning folder:
1. Make folder name consistent like other folders
2. Add link of motion-planning folder in main README
3. Make all links clickable (if they are not)
4. Any other aesthetic changes as required.

**Comment by take2rohit** [comment]
@aayush-fadia what's the update?
For your convenience, I have merged PR #7 to master. So you can directly fork this repo and start working
