### ISSUE TITLE
Create a section for interesting reads

### ISSUE THREAD

**Issue by rohant4255** [IvLabs/resources#34]
There are several nice links shared on our discord, we should consolidate them in one place and keep expanding it.
Here are some examples: 

1. http://theorangeduck.com/page/reproduce-their-results
2. https://github.com/gwisk/gradguide

**Comment by take2rohit** [comment]
We can start working on this in devel branch

**Comment by take2rohit** [comment]
Also add https://roboticstoday.github.io/

**Comment by aditya-shirwatkar** [comment]
Okie dokie

**Comment by aditya-shirwatkar** [comment]
To be Added :
1. [Mechanical Engineering Resource](https://github.com/m2n037/awesome-mecheng)
2. [HC Verma](https://www.youtube.com/playlist?list=PLK0iw6Ja-V4LeV9N3Mw1jZN8rH4DxkgPJ)

I'm not sure to which Section I should append these

**Comment by aditya-shirwatkar** [comment]
Seemed an interesting platform to me
https://jderobot.github.io/RoboticsAcademy/

**Comment by aditya-shirwatkar** [comment]
An interesting repository to look at
https://github.com/jbmouret/matplotlib_for_papers

**Comment by aditya-shirwatkar** [comment]
looks like a nice book :star_struck: 
https://github.com/rougier/scientific-visualization-book

**Comment by aditya-shirwatkar** [comment]
For controls section
https://ayonga.github.io/frost-dev/index.html
