### ISSUE TITLE
No hyperlinks of newly created folders

### ISSUE THREAD

**Issue by take2rohit** [IvLabs/resources#35]
Please add hyperlinks of folders in main `README.md` 
the folder includes `talk`,`conferences`,etc
Also need suggestions to restructure the landing page readme
i was thinking to have two sections: 
1. for _Fields in AI and Robotics_ which has all listed fields 
2. _miscellaneous_  which will have talks ,conferences, interesting reads and other stuffs!

Please give suggestions in this thread.

**Comment by aditya-shirwatkar** [comment]
Having Two Sections is a nice idea

**Comment by take2rohit** [comment]
This will be sorted out in #36
