### ISSUE TITLE
Remove redundant books 

### ISSUE THREAD

**Issue by take2rohit** [IvLabs/resources#69]
Remove books from [physics folder](https://github.com/IvLabs/resources/tree/master/physics) 

- It unnecessarily takes up space of repo. 
- Upload it to google drive and add its link in this [README.md](https://github.com/IvLabs/resources/blob/master/physics/README.md) 
- Add this books links (if available online) /add amazon links. 
- NO pirated books allowed
- Remove this file from the entire history of the repo. [HOW TO](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository)

**Comment by aditya-shirwatkar** [comment]
I'll take up the task of uploading the books on IvLabs google drive and share the links here 👍

**Comment by aditya-shirwatkar** [comment]
Here are the GDrive Links
* [A Primer of Special Relativity](https://drive.google.com/file/d/1jw5Jy_gA2OmJNCUo2R9hhPE1CWMGhx4U/view?usp=sharing)
* [Quantum Mechanics by D. J. Griffiths](https://drive.google.com/file/d/1juDEVRZL0SGMGcZUQ8eDay2_NADmsz8B/view?usp=sharing)
* [Relativistic Quantum Fields by James D. Bjorken, Sidney D. Drell](https://drive.google.com/file/d/1hkSXbbesLPzNLV2Y5NlDLQtqa8FLkLU6/view?usp=sharing)
* [Relativistic Quantum Mechanics by Dr. Walter Greiner](https://drive.google.com/file/d/1KQPJlzo-7P9RdktPnslZPbvArePcRj71/view?usp=sharing)
