### ISSUE TITLE
Add more programming languages in repo 

### ISSUE THREAD

**Issue by take2rohit** [IvLabs/resources#73]
Add different programming language tutorials for 
- Java
- Julia 
- R 
- C
- Any other popular language used in Robotics and AI 

It's not compulsory to add all languages. Add whatever you know!

Read [here](https://github.com/IvLabs/resources/blob/master/programming-languages/README.md) to get an idea on how to document.

**Comment by lovevictoria2020** [comment]
Hi! I would be interested in working on this!

**Comment by take2rohit** [comment]
Hi @lovevictoria2020.
Can you mention which programming language are you planning to add? 
You need to add best resources, tips and IDE. Also add WHY and WHERE is it popular (AI/Robotics field). 

Also add a table of content in programming language

I can assign this to you, but go through `CONTRIBUTING.md` first. Let me know what, you think. 

Thanks.

**Comment by lovevictoria2020** [comment]
Hi!

I'll add Java! 

Can you tell me a little more about what you want in the table of contents?

Thanks so much!

**Comment by take2rohit** [comment]
The table of contents will just contain the names of programming languages (hyperlinked with headings of each language)

I have assigned this issue to you. Go ahead and create a PR. 😺

**Comment by lovevictoria2020** [comment]
Sounds good! Thanks so much!

**Comment by take2rohit** [comment]
Java language added in #77
