### ISSUE TITLE
Generative Adversarial Networks

### ISSUE THREAD

**Issue by lisabecker** [IvLabs/resources#74]
I noticed that you don't have information about Generative Adversarial Networks (GANs). Would you like me to add a section about that?

**Comment by take2rohit** [comment]
Sure @lisabecker. That will be really helpful. Please go ahead and create a pul request. 
You can add them [here](https://github.com/IvLabs/resources/blob/master/deep-learning/README.md) or create a new folder named `gan`. We will review and add it 😃

**Comment by take2rohit** [comment]
Thanks for your help. Hope you liked the experience.. 
Keep Contributing and happy hacking 😸
