### ISSUE TITLE
Graph Neural Networks

### ISSUE THREAD

**Issue by RajGhugare19** [IvLabs/resources#75]
1) Add resources for GNNs and Graph representation learning
2) Add a road map for those resources

**Comment by aditya-shirwatkar** [comment]
@RajGhugare19 @take2rohit https://github.com/thunlp/GNNPapers

**Comment by aditya-shirwatkar** [comment]
@ABD-01 and others, I saw that recently you guys have created a channel on discord for this topic, it would be great if you guys document all the awesome resources here as well
